CREATE DATABASE PRUEBA_TECNICA;

USE PRUEBA_TECNICA;

CREATE TABLE PELICULA (
ID_PELICULA INT PRIMARY KEY IDENTITY,
NOMBRE NVARCHAR(50),
DURACION INT,
ESTADO BIT
);

CREATE TABLE SALA_CINE (
ID_SALA INT PRIMARY KEY IDENTITY,
NOMBRE NVARCHAR(50),
ESTADO BIT
);

CREATE TABLE PELICULA_SALA_CINE (
ID_PELICULA_CINE INT PRIMARY KEY IDENTITY,
ID_SALA_CINE INT REFERENCES SALA_CINE (ID_SALA),
FECHA_PUBLICACION DATE,
FECHA_FIN DATE,
ID_PELICULA INT REFERENCES PELICULA (ID_PELICULA)
);

GO

CREATE PROCEDURE PA_LISTA_PELICULA
AS 
BEGIN
	SELECT ID_PELICULA, NOMBRE, DURACION, ESTADO FROM PELICULA;
END;

GO

CREATE PROCEDURE PA_OBTENER_PELICULA(
@Id_Pelicula int
)
AS
BEGIN
	SELECT ID_PELICULA, NOMBRE, DURACION, ESTADO FROM PELICULA
	WHERE ID_PELICULA = @Id_Pelicula;
END;

GO

CREATE PROCEDURE PA_REGISTRAR_PELICULA(
@Nombre nvarchar(50),
@Duracion int,
@Estado bit
)
AS
BEGIN
	INSERT INTO PELICULA (NOMBRE, DURACION, ESTADO) VALUES (@Nombre, @Duracion, @Estado);
END;

GO

CREATE PROCEDURE PA_EDITAR_PELICULA(
@Id_Pelicula int,
@Nombre nvarchar(50),
@Duracion int,
@Estado bit
)
AS
BEGIN
	UPDATE PELICULA SET NOMBRE = @Nombre, DURACION = @Duracion, ESTADO = @Estado WHERE ID_PELICULA = @Id_Pelicula;
END;

GO

CREATE PROCEDURE PA_ELIMINAR_PELICULA(
@Id_Pelicula int
)
AS
BEGIN
	UPDATE PELICULA SET ESTADO = 0 WHERE ID_PELICULA = @Id_Pelicula;
END;

GO

CREATE PROCEDURE PA_BUSCAR_PELICULA(
@Nombre nvarchar(50)
)
AS 
BEGIN
	SELECT ID_PELICULA, NOMBRE, DURACION, ESTADO FROM PELICULA
	WHERE NOMBRE LIKE '%' + @Nombre + '%';
END;

GO

CREATE PROCEDURE PA_BUSCAR_NOMBRE_SALA(
@Nombre nvarchar(50)
)
AS
BEGIN
	SET NOCOUNT ON;

    SELECT S.NOMBRE AS NOMBRE_SALA,
        COUNT(PSC.ID_PELICULA) AS CantidadPeliculas,
        CASE
            WHEN COUNT(PSC.ID_PELICULA) < 3 THEN 'Sala disponible'
            WHEN COUNT(PSC.ID_PELICULA) BETWEEN 3 AND 5 THEN CONCAT('Sala con ', COUNT(PSC.ID_PELICULA), ' películas asignadas')
            ELSE 'Sala no disponible'
        END AS ESTADO_SALA
    FROM SALA_CINE S
    LEFT JOIN PELICULA_SALA_CINE PSC ON S.ID_SALA = PSC.ID_SALA_CINE
    WHERE S.NOMBRE = @Nombre
    GROUP BY S.NOMBRE
END;

GO

CREATE PROCEDURE PA_LISTA_SALA_CINE
AS 
BEGIN
	SELECT ID_SALA, NOMBRE, ESTADO FROM SALA_CINE;
END;

GO

CREATE PROCEDURE PA_OBTENER_SALA_CINE(
@Id_Sala int
)
AS
BEGIN
	SELECT ID_SALA, NOMBRE, ESTADO FROM SALA_CINE
	WHERE ID_SALA = @Id_Sala;
END;

GO

CREATE PROCEDURE PA_REGISTRAR_SALA(
@Nombre nvarchar(50),
@Estado int
)
AS
BEGIN
	INSERT INTO SALA_CINE(NOMBRE, ESTADO) VALUES (@Nombre, @Estado);
END;

GO

CREATE PROCEDURE PA_EDITAR_SALA(
@Id_Sala int,
@Nombre nvarchar(50),
@Estado bit
)
AS
BEGIN
	UPDATE SALA_CINE SET NOMBRE = @Nombre, ESTADO = @Estado WHERE ID_SALA = @Id_Sala;
END;

GO

CREATE PROCEDURE PA_ELIMINAR_SALA(
@Id_Sala int
)
AS
BEGIN
	UPDATE SALA_CINE SET ESTADO = 0 WHERE ID_SALA = @Id_Sala;
END;

GO 

CREATE PROCEDURE PA_LISTA_PELICULA_SALA_CINE
AS
BEGIN
	SELECT ID_PELICULA_CINE, ID_SALA_CINE, FECHA_PUBLICACION, FECHA_FIN, ID_PELICULA FROM PELICULA_SALA_CINE
END;

GO

CREATE PROCEDURE PA_ASIGNAR_PELICULAS_SALA_CINE(
@Id_Pelicula int,
@Id_Sala int,
@Fecha_Publicacion date,
@Fecha_Fin date
)
AS
BEGIN
	INSERT INTO PELICULA_SALA_CINE (ID_PELICULA, ID_SALA_CINE, FECHA_PUBLICACION, FECHA_FIN) VALUES (@Id_Pelicula, @Id_Sala, @Fecha_Publicacion, @Fecha_Fin);
END;

GO

CREATE PROCEDURE PA_BUSCAR_PELICULA_FECHA_PUBLICACION(
@Fecha_Publicacion Date
)
AS
BEGIN
	SELECT P.NOMBRE, PSC.FECHA_PUBLICACION FROM PELICULA P
	INNER JOIN PELICULA_SALA_CINE PSC ON P.ID_PELICULA = PSC.ID_PELICULA
	WHERE FECHA_PUBLICACION = @Fecha_Publicacion;
END;


SELECT * FROM PELICULA;